### ISSUE TITLE
showip: Use another IP address retrieval service

### ISSUE THREAD

**Issue by phihag** [AceP1983/ruTorrent-plugins#4]
This project has hardcoded the URL http://phihag.de/ip in the showip module. While I don't have any problem with occasional usage, I get millions of requests per month on that URL. Some IP addresses send 100k+ requests per month, which seems excessive by any measure - if you have that kind of bandwidth to spare, your IP address is unlikely to change every 10 seconds.

Since those requests come without a user-agent, I have no option but to suspend the entire service. Please remove my URL and replace it with your own.

**Comment by Ac3sRwild** [comment]
I apologize for the inconvenience. I am not sure how/why you were getting so many requests as the code here only grabs the ip one time when the ui is initially loaded. So it takes an actual page refresh to reload the ui and check for ip again. There is no reason that makes any sense to me for users to be constantly refreshing their page, but nevertheless I have updated the code and removed your site address.
